# Generated by Django 2.1.5 on 2019-01-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=52)),
                ('permissions', models.ManyToManyField(to='api.Permission')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('event_id', models.CharField(max_length=64)),
                ('group_id', models.IntegerField()),
                ('status', models.CharField(choices=[('AC', 'ACTIVE'), ('REV', 'REVOKED')], default='AC', max_length=8)),
                ('change_date', models.DateTimeField()),
                ('role', models.ManyToManyField(to='api.Role')),
            ],
        ),
    ]
