# Generated by Django 2.1.5 on 2019-01-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190112_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default='', max_length=512),
        ),
    ]
