# Generated by Django 2.1.5 on 2019-01-27 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190119_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='email',
            field=models.CharField(default='john.doe@gmail.com', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrole',
            name='user_name',
            field=models.CharField(default='Joh', max_length=128),
            preserve_default=False,
        ),
    ]
